name: Prune Container Registry
description: >-
  Remove outdated container images from GitHub Container Registry

branding:
  color: orange
  icon: trash-2

inputs:
  owner:
    required: true
    default: ${{ github.repository_owner }}
    description: >-
      Package owner (user or organization) name

  name:
    required: true
    description: >-
      Package name

  tag-patterns:
    description: >-
      Glob (minimatch) patterns, one per line.
      Allows applying different storage durations (`matching-tags-retention-duration` and `mismatching-tags-retention-duration`) based on tags.

  matching-tags-retention-duration:
    description: >-
      Storage duration for images with tags matching `tag-patterns`, as ISO 8601 duration.
      If more than this amount of time elapsed since last update of the image, the image will be deleted.
      If the same image (version) also has tags not matching `tag-patterns`, maximum of the two durations will be chosen.
      If not set, images with tags matching `tag-patterns` won't be deleted.

  mismatching-tags-retention-duration:
    description: >-
      Storage duration for images with tags not matching `tag-patterns`, as ISO 8601 duration.
      If more than this amount of time elapsed since last update of the image, the image will be deleted.
      If the same image (version) also has tags matching `tag-patterns`, maximum of the two durations will be chosen.
      If not set, images with tags not matching `tag-patterns` won't be deleted.

  untagged-retention-duration:
    description: >-
      Storage duration for untagged images, as ISO 8601 duration.
      If more than this amount of time elapsed since last update of the image, the image will be deleted.
      If not set, untagged images won't be deleted.

  github-token:
    required: true
    default: ${{ github.token }}
    description: >-
      GitHub API token to use

  dry-run:
    required: true
    default: 'false'
    description: >-
      Output the list of images that would be deleted, instead of deleting them

outputs:
  deleted-count:
    description: >-
      Deleted image count

  deleted-json:
    description: >-
      Deleted "package versions" as JSON array

runs:
  using: node20
  main: dist/index.js
